// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });


import './layout.scss';
import PageLayout from './layoutClient';

export const metadata = {
  title: "Amrit Masonic Special School",
  description: "Generated by create next app",
}



export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <PageLayout>
          { children }
        </PageLayout>
      </body>
    </html>
  )
}

